# Generated by Django 5.2.1 on 2025-05-19 15:57

import django.db.models.deletion
import transaction.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_user_options_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_limit",
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="week_limit",
            field=models.DecimalField(decimal_places=2, default=35000, max_digits=10),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRANSPORT", "Transport"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("UTILITIES", "Utilities"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        validators=[transaction.validators.time_validation],
                        verbose_name="Время",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[transaction.validators.negative_amount],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
