# Generated by Django 5.2.1 on 2025-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_user_daily_limit_user_week_limit_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Food"),
                    ("TRANSPORT", "Transport"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("UTILITIES", "Utilities"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
